//
//  ViewController.swift
//  FantasyFootballProject
//
//  Created by John on 4/30/18.
//  Copyright © 2018 John Bruggeman. All rights reserved.
//

import UIKit

class ViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate {
    
    @IBOutlet weak var tableView: UITableView!
    
    @IBOutlet weak var searchBar: UISearchBar!
    
    var name = ["Jared Goff","Dalvin Cook", "Ryan Tannehill", "Doug Baldwin","LeSean McCoy","Jay Ajayi","Aaron Rodgers","Mike Evans","Tom Brady","Michael Thomas","Carson Wentz","Keenan Allen","Rob Gronkowski","Derrick Henry","Joe Mixon","Mark Ingram","Ameer Abdullah","Derek Carr","Jordy Nelson","John Ross","Eddie Lacy","Jarvis Landry","Mike Gillislee","Dak Prescott","DeAndre Hopkins","Doug Martin","Corey Coleman","Mitch Trubisky","Bilal Powell","Spencer Ware","Ezekiel Elliott","O.J. Howard","Melvin Gordon","A.J. Green","Andrew Luck","Blake Bortles","Ben Roethlisberger","David Johnson","Joe Flacco","Le'Veon Bell","Alvin Kamara","Jordan Reed","Antonio Brown","D'Onta Foreman","Brandin Cooks","JuJu Smith-Schuster","Samaje Perine","Travis Kelce","Corey Davis","Kirk Cousins","Matt Ryan","Kelvin Benjamin","DeSean Jackson","Marshawn Lynch","Dez Bryant","Jordan Howard","Amari Cooper","Lamar Miller","Kareem Hunt","Marcus Mariota","Emmanuel Sanders","Tyrod Taylor","Bengals D/ST","Jimmy Graham","Matthew Stafford","Will Fuller","Ravens D/ST","Greg Olsen","Odell Beckham Jr.","Christian McCaffrey","Carlos Hyde","Davante Adams","Alshon Jeffery","Russell Wilson","Allen Robinson","Andy Dalton","Deshaun Watson","David Njoku","Leonard Fournette","Sammy Watkins","Cam Newton","Julio Jones","Todd Gurley","Jamison Crowder","Eli Manning","Evan Engram","Hunter Henry","Drew Brees","Devonta Freeman","Stefon Diggs","T.Y. Hilton","Demaryius Thomas","Jameis Winston","Tyler Eifert","Martavis Bryant","Sam Bradford","Randall Cobb"]
    
    var position = ["QB", "RB", "QB", "WR","RB", "RB","QB","WR","QB","WR","QB","WR","TE","RB","RB","RB","RB","QB","WR","WR","RB","WR","RB","QB","WR","RB","WR","QB","RB","RB","RB","TE","RB","WR","QB","QB","QB","RB","QB","RB","RB","TE","WR","RB","WR","WR","RB","TE","WR","QB","QB","WR","WR","RB","WR","RB","WR","RB","RB","QB","WR","QB","D/ST","TE","QB","WR","D/ST","TE","WR","RB","RB","WR","WR","QB","WR","QB","QB","TE","RB","WR","QB","WR","RB","WR","QB","TE","TE","QB","RB","WR","WR","WR","QB","TE","WR","QB","WR"]
    
    var salary = [2.00, 4.00,8.00,28.00,46.00,46.00,53.00,65.00,32.00,40.00,19.00,13.00,45.00,10.00,4.00,22.00,7.00,45.00,54.00,4.00,12.00,20.00,20.00,45.00,38.00,8.00,8.00,2.00,13.00,11.00,80.00,4.00,56.00,59.00,54.00,13.00,32.00,61.00,11.00,54.00,4.00,31.00,64.00,2.00,43.00,2.00,4.00,23.00,4.00,31.00,37.00,12.00,2.00,35.00,40.00,40.00,56.00,41.00,2.00,43.00,22.00,20.00,2.00,5.00,30.00,4.00,2.00,13.00,69.00,4.00,17.00,24.00,23.00,37.00,26.00,14.00,2.00,2.00,4.00,23.00,41.00,76.00,56.00,10.00,9.00,2.00,5.00,43.00,44.00,6.00,45.00,23.00,30.00,10.00,7.00,2.00,2.00]
    
    var yearsLeft = [1,1,1,2,2,3,3,3,3,3,3,2,1,2,1,1,1,3,2,1,1,2,1,3,3,1,1,1,1,2,3,1,3,2,3,2,1,3,1,3,1,3,3,1,2,2,1,2,1,3,2,1,1,3,2,3,3,2,1,3,1,3,1,1,1,3,1,1,2,3,1,2,2,1,3,2,2,1,1,1,2,3,3,3,1,2,1,1,1,2,2,1,3,2,1,1,1]
    
    var owner = ["JB Bruggeman", "JB Bruggeman",  "JB Bruggeman","JB Bruggeman","JB Bruggeman", "JB Bruggeman","JB Bruggeman", "JB Bruggeman","Justin Ingram","Justin Ingram","Justin Ingram","Justin Ingram","Justin Ingram","Justin Ingram","Justin Ingram","Justin Ingram","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Jack Forsman","Edward Ruby","Edward Ruby","Edward Ruby","Edward Ruby","Edward Ruby","Edward Ruby","Cooper Burrill","Cooper Burrill","Cooper Burrill","Cooper Burrill","Cooper Burrill","Cooper Burrill","Cooper Burrill","Parker Whims","Parker Whims","Parker Whims","Parker Whims","Parker Whims","Parker Whims","Parker Whims","Parker Whims","Parker Whims","Parker Whims","Parker Whims","Parker Whims","Michael Fontaine","Michael Fontaine","Michael Fontaine","Michael Fontaine","Michael Fontaine","Michael Fontaine","Michael Fontaine","Michael Fontaine","Michael Fontaine","Michael Fontaine","Michael Fontaine","Ethan Heerwagen","Ethan Heerwagen","Ethan Heerwagen","Ethan Heerwagen","Ethan Heerwagen","Ethan Heerwagen","Ethan Heerwagen","Ethan Heerwagen","Ethan Heerwagen","Ethan Heerwagen","Ethan Heerwagen","Ethan Heerwagen","Jack Bullard","Jack Bullard","Jack Bullard","Jack Bullard","Jack Bullard","Jack Bullard","Jack Bullard","Jack Bullard","Jake Rogers/Liam McCarthy","Jake Rogers/Liam McCarthy","Jake Rogers/Liam McCarthy","Jake Rogers/Liam McCarthy","Jake Rogers/Liam McCarthy","Jake Rogers/Liam McCarthy","Jake Rogers/Liam McCarthy","Jake Rogers/Liam McCarthy","Jake Rogers/Liam McCarthy","Jake Rogers/Liam McCarthy","Jake Rogers/Liam McCarthy"]
    
    var rotoworldBlurb = ["Jared Goff completed 24-of-45 passes for 259 yards and a touchdown in the Rams' 26-13, Wild Card loss to the Falcons. Unable to connect with pass catchers not named Robert Woods or Cooper Kupp, it was a quiet end to Goff's promising sophomore campaign. Although still strangely inaccurate on many easy throws, Goff was better across the board in 2017. Too much credit can be given to coaching, but Sean McVay's presence was undoubtedly the driving force behind Goff's improvement. McVay relentlessly featured play action, and famously called audibles into Goff's headset down to the 15-second mark on the play clock. Goff remains far from a finished product. It's still possible, if not likely, he does not end up a true franchise quarterback. Amongst other things, he must improve his accuracy from the pocket. The takeaway is that he's left his dismal rookie campaign in the rear-view mirror, and has plausible steps he can take forward.",
                          "Vikings trainer Eric Sugarman said Dalvin Cook (knee) has 'knocked the rehab out of the park' in his return from a torn ACL. 'He'll participate in (OTAs and minicamp) on a limited basis,' Sugarman said. 'Then the plan is for him, hopefully when he gets to training camp, he’ll be a participant just like everybody else.' It sounds like Cook is just about ready, but the team is going to bring him slowly through spring work with an eye toward having Cook ready to roll this summer. Cook is an RB1 heading into 2018.",
                          "NFL Network's Tom Pelissero reports the Dolphins have assured Ryan Tannehill (knee) he will start in 2018 even if they draft a quarterback in the first round. Pelissero reports the Dolphins would consider moving up if a quarterback begins to slip, but the 'smart money says they stand pat at 11 [and] take the best available defensive player.' Miami was strongly linked with Oklahoma QB Baker Mayfield early in the draft process, but it looks like he will come off the board well before their pick, perhaps even No. 1 overall. Tannehill was having his best season as a pro before going down with a knee injury late in 2016, and that same knee caused him to miss all of 2017. With uncertainty about Tannehill's health and ability to be a top-flight quarterback, it makes sense for the Dolphins to grab one of the premier quarterbacks if they can.",
                          "Doug Baldwin caught 4-of-5 targets for 90 yards and two touchdowns in the Seahawks' Week 17 loss to the Cardinals.With the 90 yards, Baldwin fell nine short of his third-straight 1,000-yard campaign. He did score a pair of spectacular touchdowns, giving him eight on the year and at least seven each of the past three seasons. Baldwin isn't quite a true No. 1, but has tough hands and elite body control. Going on 30, he has not lost a step, and will remain a high-end WR2 for fantasy purposes in 2018.",
                          "LeSean McCoy set a five-year low in percentage of carries from shotgun formations in 2017. Just 17 percent of McCoy's carries came out of the 'gun, a far cry from the 83 percent he logged way back in 2013 under Chip Kelly. Partly as a result, McCoy averaged a career-worst 3.97 yards per carry. McCoy has always been an elusive in-space creator and not a physical grinder between the tackles, and shotgun runs give him more room at the handoff. The 2017 Bills offensive staff failed badly to mold their scheme to their player talents, resulting in OC Rick Dennison's post-season dismissal.",
                          "Jay Ajayi rushed nine times for 57 yards in the Eagles' Super Bowl 52 win over the Patriots.Ajayi’s biggest play was a 26-yard burst on a third-and-four run in the second quarter. He was out-touched 14 to 9 by LeGarrette Blount, albeit deservedly because Blount ran so well. Still, it was a change from the Eagles’ previous backfield distribution. Acquired from the Dolphins for a fourth-round pick before Week 9, Ajayi wound up earning lead back duties but stayed in a rotation with Corey Clement and Blount. Coach Doug Pederson has long shown an affinity for committee backfields over feature backs. Ajayi did log 16-plus touches in four of Philly’s last six games and should expect a similar workload entering the 2018 season, which will be Ajayi’s contract year.",
                          "Yahoo Sports' Charles Robinson reports Aaron Rodgers is both 'frustrated' and 'emotional' because he was not consulted before the Packers made some significant personnel decisions this offseason.Robinson reports the specific moves which have Rodgers miffed are the decisions to cut ties with Jordy Nelson and QBs coach Alex Van Pelt. 'Both of those decisions were made without him,' a source told Robinson. 'In both situations, he had no influence with [the front office] before anything went down.' Rodgers made some noise about the Van Pelt decision when it happened, calling it 'curious' and 'interesting' before making it clear he was not consulted about the move. There clearly seems to be some friction between Rodgers and the front office, and that could prove troublesome as the two sides look to work out a mega-extension this summer. Rodgers has two more years left on his deal.",
                          "Buccaneers signed WR Mike Evans to a five-year, $82.5 million contract extension. The deal includes $55 million guaranteed and keeps Evans under contract through 2023. In terms of annual salary, this makes Evans the second-highest-paid receiver in football behind future Hall of Famer Antonio Brown. Evans is coming off a down year in 2017, but still topped 1,000 yards receiving for the fourth time in as many seasons. Odell Beckham, who was drafted five picks after Evans in 2014, could use Evans' new deal as a starting point in long-term negotiations with the Giants.",
                          "Tom Brady's agent fully expects his client to return for the 2018 season. The 'Brady might retire' story appeared mortally wounded mere hours after it arrived in the world, but it now sounds officially dead. Brady forcing the Patriots' hand with Jimmy Garoppolo and then retiring would have been an all-time betrayal. It also never seemed to have an actual chance of happening. Fresh off winning an MVP award at age 40 and throwing for over 500 yards in the Super Bowl, Brady will enter 2018 remaining one of the very best players in the league.",
                          "Michael Thomas nabbed seven-of-13 targets for 85 yards and two touchdowns Sunday in the Saints' Divisional Round loss to the Vikings. Thomas got off to an inauspicious start on Sunday. He caught just two passes in the first half and wasn't even targeted until the second quarter while being shadowed by All-Pro cornerback Xavier Rhodes. But Thomas would not be denied in the second half, burning Minnesota for 54 yards after halftime as the Saints erased a 17-point deficit, only to lose on the game's final play. He beat Rhodes on his first touchdown, a 14-yarder, before schooling Terence Newman on a three-yard slant for his second score of the game. Keyshawn Johnson's nephew only scored five touchdowns during the regular season but went over 1,000 yards for the second straight year while setting a team record with 104 catches. He should be one of the first receivers off the board in fantasy drafts next summer.",
                          "Carson Wentz (ACL) has advanced to running. Wentz believes he's still on track for Week 1, though it doesn't sound like he expects to play in the preseason. The 25-year-old also said he doesn't plan on changing his aggressive playing style despite tearing his ACL late last season. Only Seattle's Russell Wilson threw for more touchdown passes than Wentz in 2017.",
                          "Associated Press named Chargers WR Keenan Allen its 2017 Comeback Player of the Year.Allen had been healthy for only nine games over the past two seasons. He came back from a torn ACL to play in all 16 games last year, catching 102 passes for 1,393 yards and six touchdowns. Allen had seven 100-yard games and at least 40 yards in 15-of-16 weeks. He's the second straight receiver to win the award after Jordy Nelson took home the 2016 honors. Still just entering his prime, 25-year-old Allen is locked in Philip Rivers' top target going into next season.",
                          "Rob Gronkowski announced in a Tuesday social media post that he will return for the 2018 season.'I met with coach today and informed him I will be back for the 2018 season with the Pats,' Gronk posted on Instagram, under his @gronk handle. 'I have been working out, staying in shape and feel great.' The fact that Gronkowski met with coach Bill Belichick on Tuesday to inform him of his intentions confirms he was seriously considering stepping away. Although Gronk is still only 29 (next month), he has dealt with a litany of serious injuries during his eight seasons in the NFL. At this point, he should be considered a year-to-year proposition going forward, something to be mindful of in Dynasty leagues.",
                          "Following Thursday's release of DeMarco Murray, third-year pro Derrick Henry is now locked in as the Titans' lead back. Locked into a 2017 timeshare with an ineffective Murray, Henry was up and down, but generally excelled with bigger workloads. He was one of the league's best clock-killing backs, punishing defenses in the second half. He averaged 5.1 yards per carry after the break as opposed to 3.1 before. Henry is still a question mark in the passing game, but should have at least the first two downs on lockdown. He's a potential first-round pick in fantasy leagues.",
                          "Joe Mixon currently weighs 225 pounds and is 'looking to drop five more.' Mixon weighed nearly 240 pounds at rookie minicamp last year after letting his conditioning go temporarily due to pre-draft travel, visiting several NFL teams. This offseason, Mixon has been able to stay in better shape with a one-track focus as he prepares to take over as the Bengals' full-time feature back.",
                          "Mark Ingram has switched agents. After being represented for a number of years by Joel Segal of Lagardere Sports and Entertainment, Ingram is now with Paul Bobbitt and David Jones of VIP Sports Management. The 28-year-old broke out for career-highs in both rushing yards (1,124) and touchdowns (12) last season while splitting backfield work with Rookie of the Year Alvin Kamara. Ingram's contract expires after 2018.",
                          "ESPN's Michael Rothstein said it would not be a 'surprise' if the Lions shopped Ameer Abdullah. Of Detroit's current running backs, Rothstein believes only LeGarrette Blount's roster spot is safe. Abdullah opened last season as the Lions' lead back but saw his role diminish as the year went on. With the Lions expected to pursue a running back early in next week's draft, Abdullah's days in Detroit could be numbered. The former second-round pick will earn $876,745 in the final year of his rookie contract.",
                          "Derek Carr admitted his back injury affected him throughout the season. Carr never looked the same after suffering the injury in Week 4. 'When you break three bones in your back, it doesn’t feel good,' he said. 'I had to deal with it.' Carr probably came back too soon, missing just one game after originally being given a 2-4 week recovery window. The 26-year-old will have his work cut out for him in 2018 working under demanding head coach Jon Gruden.",
                          "Raiders signed WR Jordy Nelson, formerly of the Packers, to a two-year, $15 million contract. As expected, the Raiders cut Michael Crabtree and his $7.5 million in salary and bonuses for 2018 and gave it to Nelson, who gets $13 million guaranteed. Nelson (33 in May) is two years older than Crabtree and looked washed with the Packers last season, though we're going to give him the benefit of the doubt for now, considering he was playing with Brett Hundley. (It didn't bother Davante Adams.) Nelson will be the starter opposite Amari Cooper, who coach Jon Gruden said will be the focal point of the offense. Consider Nelson a WR3 for now.",
                          "John Ross has been training with former Bengals WR T.J. Houshmandzadeh in Long Beach. Houshmandzadeh sees huge potential in Ross despite a disastrous rookie year that saw him go the entire season without catching a single pass. 'If he’s working with me, bet your house on him,' said Houshmandzadeh, an 11-year NFL vet who spent the bulk of his career in Cincinnati. Specifically, Houshmandzadeh wants to iron out Ross' route-running while improving his footwork. 'You get to this level, everybody can run,' he said. 'Your technique and ability to separate has to come to the forefront because you can’t beat everybody with speed.' Ross logged just 17 snaps as a rookie while battling knee and shoulder injuries.",
                          "The Seahawks don’t plan to re-sign free agent Eddie Lacy. This is expected after Lacy finished the final weeks of 2017 as a healthy scratch. Coming off a down year with a history of conditioning issues, Lacy is going to struggle for guaranteed money this offseason. The Seahawks have a healthy Chris Carson returning and look likely to add a running back in the draft",
                          "Browns signed Jarvis Landry to a five-year, $75.5 million extension through 2023. ESPN's Josina Anderson was the first to report the impending deal. NFL Network's Ian Rapoport reports the contract includes $47 million guaranteed, and Landry is now the fifth-highest paid receiver in the league based on average salary. It is a shocking price to pay for a volume-based player who never elevated Miami's passing attack past mediocre, but Landry at worst can be a reliable safety blanket for whichever quarterback Cleveland selects with the No. 1 overall pick.",
                          "Ben Volin of the Boston Globe believes Mike Gillislee will get 'another shot' with the Patriots next season. With Dion Lewis expected to leave in free agency and Rex Burkhead also hitting the market, the Patriots are in need of an early-down ball-carrier. Gillislee certainly fits that description, though he's coming off an underwhelming year that saw him as a healthy scratch for much of the second half. The 27-year-old does have a nose for the end zone with 14 touchdowns (13 rushing, one receiving) over his last two seasons. Scheduled to earn just $1.9 million in 2018, New England can afford to retain Gillislee while also gauging the market for other backs. C.J. Anderson could be an option for the Pats if he's released by Denver.",
                          "Dak Prescott completed 17-of-30 passes for 179 yards and a touchdown in Week 17 against the Eagles. After a strong start, Prescott faded in the second half, finishing with an 8:9 TD/INT ratio over the final eight games. Outside of his rushing stats, he took a step back across the board from his rookie year. With a full season of Ezekiel Elliott, Prescott is set up for a better 2018, but he's not a top-15 quarterback. Dallas should look to improve Prescott's supporting cast this offseason.",
                          "Texans declared WR DeAndre Hopkins, QB Josh Johnson, LB LaTroy Lewis, WR DeAndrew White, RB Jordan Todman, OT Kendall Lamm, and RG Jeff Allen inactive for Week 17 against the Colts. Hopkins misses his first career game with a calf issue after starting his first 79 games. He had a down 2016 with Brock Osweiler under center, finishing with just 954 yards and four scores, but Hopkins rebounded in a big way in 2017 no matter who was playing quarterback for the Texans. Hopkins set a new career high with 13 touchdowns to lead all receivers and finishes four catches shy of his second 100-catch year. His 1,378 yards are second-best in his five seasons. Hopkins signed a massive extension in August and is under contract through 2022. With Deshaun Watson coming back in 2018, the sky is the limit for Hopkins who could seriously flirt with 20 touchdowns.",
                          "Raiders signed RB Doug Martin, formerly of the Bucs, to a one-year contract. Although Martin is coming off a stupendously-bad year, it could be an indication the Raiders are moving on from Marshawn Lynch. That's been hinted at for weeks. New Raiders coach Jon Gruden never coached Martin in Tampa but seems to have remained something of a Bucs partisan. Martin has a three-down skill-set when right but is one of the most inconsistent players in the NFL. Off-the-field issues have played a part. The Raiders are hoping a 29-year-old back who has had some great seasons is ready to make the most of a new opportunity. Martin will not be handed anything in a backfield that includes DeAndre Washington and Jalen Richard in addition to Lynch.",
                          "ESPN Cleveland's Tony Grossi characterized Corey Coleman's future with the Browns as 'uncertain.'Coach Hue Jackson's initial first-round pick in Cleveland, Coleman was selected 15th overall in 2016. He has missed 13 of a possible 32 games to a pair of broken hands. When on the field, Coleman has produced just one 100-yard game, with two of his five career touchdowns coming that afternoon. Coleman is now facing an off-field matter stemming from a 2016 New Year's Eve incident and ended 2017 on a horrible note with an awful dropped pass to seal the Browns' 0-16 season. Coleman is under team control for three more years but could be on the block.",
                          "Mitchell Trubisky completed 20-of-36 passes for 178 yards, zero touchdowns and zero interceptions in the Bears' 23-10, Week 17 loss to the Vikings. The 23-year-old No. 2 overall pick finishes his rookie year with just nine total touchdowns across 12 starts. Trubisky completed 59.3 percent of his passes and averaged 6.64 yards per attempt. They're truly dismal numbers, though Trubisky did goose his stats with 41/248/2 on the ground. Receiving near league-worst coaching and receiver play, Trubisky merits an 'incomplete' grade for his rookie campaign. He showed some intriguing flashes with his athleticism and arm. The Bears will hope they can make Trubisky 2018's Jared Goff with direly-needed improvements at coach and wideout.",
                          "ESPN's Rich Cimini reports the Jets view Bilal Powell as a 'complementary back.' Cimini went on to say he believes that Powell will continue to share the workload with either Elijah McGuire or someone else they bring in. Despite Matt Forte likely to be cut, it doesn't look like Powell's workload will increase much if at all. His receiving upside leaves him in play as a late pick in 2018 fantasy drafts.",
                          "Chiefs coach Andy Reid was vague when asked about Spencer Ware's (PCL, MCL) health on Monday. Reid first stated he expected Ware to be ready for training camp, then later backtracked and said 'you never know.' Reid indicated Ware participating in any football activities before training camp would be a surprise. Since last season ended, the Chiefs have added two veteran backs in Damien Williams and Kerwynn Williams, hinting at concern over Ware's recovery.",
                          "Ezekiel Elliott rushed 27 times for 103 yards in Week 17 against the Eagles. It ends a drama filled sophmore year for Elliott, who spent half the season battling the NFL over his suspension. When on the field, Elliott wasn't the same back he was as a rookie, averaging just 4.0 YPC. Elliott had at least 20 touches in 9-of-10 games, so he's still the centerpiece of the Cowboys' offense with no threat for carries. Elliott is a good bet to rebound in 2018, but his off-field baggage remains a concern for his Dynasty outlook.",
                          "Bucs placed TE O.J. Howard on injured reserve with an ankle injury, ending his season. Howard injured his foot on a 30-yard touchdown grab in Monday night's loss to the Falcons. The No. 19 overall pick back in April, Howard got off to a slow start (expectedly) but finished his rookie season with 26 grabs for 432 yards (16.6 YPR) and six touchdowns. With better quarterback play and a season under his belt, Howard will likely be looked at as a 2018 breakout candidate.",
                          "Chargers GM Tom Telesco confirmed Melvin Gordon's fifth-year option will be picked up. Gordon averaged below 4.0 yards per carry in each of his first three years, but the Bolts are comfortable with his progress in the passing game and ability to handle a near-full workload. Gordon is again on track to be a first-round fantasy pick, although the Chargers have openly stated they are interested in adding a running back. Gordon turned 25 earlier this month.",
                          "A.J. Green will not play in the Pro Bowl because of a knee injury. The issue is reportedly minor and will not require surgery, suggesting it is just an excuse for Green to skip the game. He should be fine for the offseason program.",
                          "Colts GM Chris Ballard said he's turned down multiple trade offers for Andrew Luck (shoulder). Ballard said he received calls on Luck at last year's trade deadline, though he declined to name which teams were interested. Obviously it's a moot point as Luck, surgically-repaired shoulder and all, isn't going anywhere. 'We’re not trading Andrew Luck,' said Ballard. 'I’m not putting that on my résumé.' Luck has yet to resume throwing an actual football, though he seems to be making progress. Ballard remains adamant that Luck will be ready for Week 1.",
                          "Jaguars coach Doug Marrone said Blake Bortles (wrist) is training 'pain-free.' Marrone added Bortles is working with 'no limitations.' The quarterback said he would be ready to go for OTAs, and it appears as if he is on track to fulfill that promise. Bortles was given a three-year, $54 million extension last month",
                          "Steelers owner Art Rooney is open to extending Ben Roethlisberger. 'His play this year makes you feel he does have a few years left,' Rooney said. 'All that is great in terms of the contract. We'll address that at the right time. Bottom line is we're excited and we'll continue to work with him.' After retirement rumors last offseason, Roethlisberger plans to play for at least three more years. The Steelers have Roethlisberger signed through 2019.",
                          "Cardinals coach Steve Wilks said David Johnson (wrist) is expected to be ready for OTAs. It is not a surprise after Johnson was deemed 100 percent healthy in January. A new coaching staff brings some uncertainty, but a Johnson should still dominate the backfield work in Arizona.",
                          "Coach John Harbaugh said after the Ravens selected Lamar Jackson No. 32 overall that Joe Flacco 'is our quarterback.' 'Lamar is going to have a great chance to develop,' Harbaugh continued. 'This doesn't really change things in a sense that we're going to go with Joe and he's going to roll.' Flacco turned 33 in January and has been mediocre at best since tearing his ACL a couple years back. He has four years left on his contract, but the Ravens can clear $18.5 million against the cap next year by cutting him. They're not going to do that, but a 2019 trade seems very likely.",
                          "Franchise player Le'Veon Bell did not report for the Steelers' offseason program this week. These 'practices' are voluntary, and it was widely expected that Bell wouldn't report, as he remains unsigned on the franchise tag for the second consecutive year. Contract talks have completely stalled and possibly broken off. The sides have until mid-July to hammer out a long-term deal, one that looks like a long shot right now. Bell would then likely skip training camp as well.",
                          "Associated Press named Saints RB Alvin Kamara its 2017 Rookie of the Year. Kamara won a close race with rushing leader Kareem Hunt, who finished with 21 first-place votes. Despite playing in a timeshare with Mark Ingram, Kamara had 1,554 total yards (728 rushing, 826 receiving) and 81 catches while averaging an NFL-best 6.1 YPC. His 13 touchdowns were behind only Todd Gurley (19). Kamara also ranked second in missed tackles (58) and yards after contact per carry (3.8) in one of the more impressive all-purpose seasons. Returning to a top-five offense, Kamara should build on his rookie season in 2018.",
                          "Redskins coach Jay Gruden said Jordan Reed had a 'procedure done on his toes.'It explains why he is not expected to participate in OTAs. Reed ended the season on injured reserve because of a hamstring issue, but he was limited by a toe problem during training camp last year. Hopefully this procedure fixes the issue for good, but even if it does, Reed will remain one of the biggest injury risks in fantasy. The tight end has never played more than 14 games in a season.",
                          "Antonio Brown caught 7-of-11 targets for 132 yards and two touchdowns in the Steelers' Divisional Round loss to the Jaguars. Although he lacked his usual explosiveness playing through a calf injury, Brown put on a highlight-reel performance with superb route running and sticky hands. He scored the Steelers’ first points of the game on a 23-yard basket catch against A.J. Bouye, who didn’t allow a touchdown all season. Later, Brown ripped a 27-yard gain on a crosser in front of Jalen Ramsey, then beat Bouye again on a spectacular, falling-backwards 43-yard TD on fourth-and-five. Brown once again finished as the No. 1 overall fantasy receiver in 2017 and should remain a top-five pick in 2018 fantasy drafts.",
                          "Texans RB D'Onta Foreman could begin the season on the reserve/PUP list. That would make him unavailable for the team's first six regular season games. Foreman tore his Achilles in November but has since been setback-free and rumored to be ready for Week 1. A healthy preseason would not only prove his readiness for the regular season, it could also allow Foreman to open 2018 in a starting role over teammate Lamar Miller.",
                          "NFL Network's Steve Wyche reports the Rams plan to sign contract-year WR Brandin Cooks to an extension prior to the season. Jared Goff and Cooks have been training together this offseason and share the same agent, so perhaps there have already been discussions with Cooks' representation. He's a West Coast guy who grew up in Stockton, Cali. and played his college ball at Oregon State. Cooks won't come cheap, however, and should command around the $16 million per year Sammy Watkins got. But all signs point to the two sides hammering out a deal after the Rams gave up a first-rounder.",
                          "JuJu Smith-Schuster caught 3-of-5 targets for five yards and a touchdown in the Steelers' Divisional Round loss to the Jaguars. Bottled up by underrated Jaguars slot CB Aaron Colvin, Smith-Schuster escaped with box-score production only because he caught what amounted to a garbage-time touchdown. It was a quiet ending to a sensational rookie campaign in which Smith-Schuster tallied a 58/917/7 receiving line, averaging a robust 15.8 yards per catch and drawing comparisons to early-career Hines Ward as a rugged, versatile route runner. As he just turned 21 in late November, the sky is the limit for Smith-Schuster long term. He'll be a WR2 target in 2018 re-draft leagues.",
                          "Redskins senior VP of player personnel Doug Williams said there's 'no doubt about it. We need to upgrade at running back.' Samaje Perine, Rob Kelley, and Chris Thompson currently make up the Redskins' running back room. Kelley and Perine both disappointed in 2017, rushing a combined 237 times for 797 yards (3.36 YPC) and four TDs. Pass-game specialist Thompson is coming off a broken leg. Kelley probably faces an uphill battle for a roster spot. Perine is penciled in as the starter, but the Redskins surely have an eraser handy.",
                          "Travis Kelce exited the Wild Card playoff game against the Titans with a concussion and will not return. Kelce took a big hit to the head from Johnathan Cyprien late in the second quarter and could even stand up and walk on his own after the brain injury. Eventually, Kelce was able to gather himself and jog to the sideline before immediately being sent to the locker room. Kelce caught all four of his targets for 66 yards and a touchdown before leaving.",
                          "Corey Davis caught 5-of-8 targets for 63 yards and two touchdowns in the Titans' blowout Divisional Round loss to the Patriots. Davis got the Titans on the board with a one-handed touchdown catch from 15 yards out in the first quarter, beating Patriots CB Malcolm Butler. It was Davis’ first career score after he failed to hit pay dirt in 11 regular season appearances. Davis beat Butler again for a touchdown in garbage time. The fifth overall pick in last April’s draft, Davis managed a 34/375/11.0/0 receiving line as a rookie, flashing at times but struggling with persistent hamstring injuries and ultimately lacking a consistent rapport with Marcus Mariota. Nevertheless, Davis has a bright future as a Brandon Marshall-type talent. He will be a popular 2018 fantasy breakout pick. ",
                          "Vikings signed Kirk Cousins, formerly of the Redskins, to a three-year contract. The deal is believed to be for around $86 million, and ESPN's Adam Schefter reports it will be fully-guaranteed, a landmark for an NFL free agent. The contract is expected to be finalized after Cousins visits the Vikings' facility on Thursday. It always made sense for Cousins to land in Minnesota, an organization with a strong roster and good coaching which gives him a chance to win right away. This is also an ideal spot for Cousins from a fantasy perspective. With Adam Thielen, Stefon Diggs, and Kyle Rudolph to target and Dalvin Cook in the backfield, Cousins looks like a locked-in QB1.",
                          "Falcons GM Thomas Dimitroff said a contract extension for Matt Ryan is 'close.' Contract talks reportedly 'hit a snag' last month, but it sounds as if that has been worked out. Dimitroff said the negotiations are 'not a complicated process' and he is 'not kept up at night.' It would be a surprise if Ryan does not have a new deal once training camp rolls around.",
                          "Bills GM Brandon Beane said he wants to see how Kelvin Benjamin fits in the new offense before discussing a contract extension. Benjamin is entering the final year of his rookie deal. In addition to his fit, Beane likely wants to see how healthy and in shape Benjamin is before discussing a long-term deal. Benjamin caught 16 passes for 217 yards and a touchdown in six games with the Bills last year after coming over from Carolina via a trade, although he was never really healthy during that run.",
                          "DeSean Jackson and Jameis Winston plan to work out together this offseason. After coach Dirk Koetter criticized the quarterback for not getting Jackson the ball, Winston made it a goal to improve his chemistry with the speedy receiver this offseason. 'Me and DeSean, we have spent a lot of time together this offseason whether it was on the phone, Facetime or even at his house,' Winston said. 'We're going to find times and slots where we can work outside of the facility to help build our connection.' Jackson is a good bet to improve on his 50/668/3 line from a season ago.",
                          "NFL Network's Tom Pelissero reports Marshawn Lynch took a $500,000 pay cut from the Raiders before a $1 million roster bonus was due on Saturday. Lynch was previously guaranteed no money on the deal, but according to Pelissero, Lynch is now essentially guaranteed $4.5 million thanks to the restructure and has a base value of $5.5 million for 2018. It locks Lynch into the Raiders this season after there had been previous speculation he may be released. Lynch will remain the starter, with Doug Martin competing for a backup job.",
                          "Bills GM Brandon Beane said the team won't pursue free agent Dez Bryant. Beane said the Bills watched Bryant on tape but won't pursue the free agent any further. 'If we thought that was the right fit for us, we definitely would potentially pursue it,' Beane continued. Bryant reportedly turned down a multi-year contract from the Ravens recently and continues to seek out a one-year, prove-it deal. The Cardinals and Packers have been linked to Bryant, though nothing concrete has materialized to this point. ",
                          "Bears coach Matt Nagy confirmed that Jordan Howard will be the team's 'featured' back. He'll lead the backfield, though Nagy said the team plans to use multiple backs. Howard has averaged an impressive 4.6 yards per carry since arriving as a fifth-round draft pick in 2016, though he's been a sub-par receiver with 14 drops during that span. The 23-year-old won't lack for touches, though we suspect Tarik Cohen will see plenty of work on passing downs this season.",
                          "Raiders exercised WR Amari Cooper's fifth-year team option for 2019. There was some manufactured drama over whether the Raiders would extend Cooper's rookie contract by a year, but this was always going to be the outcome. Slated to make $3.53 million this season, Cooper will be due roughly $13.9 million in 2019. The option is guaranteed for injury only, meaning the Raiders could still walk away unless Cooper fails his physical before the start of the next league year. Wildly inconsistent through his first three NFL campaigns, 24-year-old (in June) Cooper has nevertheless already posted two 1,000-yard seasons.",
                          "The Texans could release Lamar Miller. Miller had a career worst 3.7 YPC last season after fading down the stretch in 2016. Owed $14 million over the next two years, he’s not a lock to be back. D’Onta Foreman was pushing Miller for touches before landing on IR and gives the Texans an in-house replacement if they move on. Even if Miller returns, it’s possible he’ll be shifted into more of a pass game role. The Texans can save $5.75 million from making Miller a post June cut.",
                          "Coach Andy Reid said he hopes to involve Kareem Hunt more in the passing game. Reid said he liked Hunt finishing with 325 touches, and 'We probably need to expand on his role in the pass game,' where Hunt caught 53 passes but lost third-down and two-minute duties to Charcandrick West. Particularly in PPR leagues, Hunt's fantasy stock will benefit if he sees a meaningful uptick in targets. Spencer Ware's status remains uncertain after last year's multi-ligament knee injury.",
                          "Titans exercised QB Marcus Mariota's 2019 fifth-year option. This was an absolute no-brainer move, obviously. The No. 2 overall pick in the 2015 draft, Mariota has yet to play a full 16-game regular season due to injuries, but he's missed just two contests over the past two years, though he was noticeably hampered in several others. His 13 touchdown passes across 15 games last season made for extreme disappointment, but the Titans have brought in a forward-thinking offensive staff this year, led by OC Matt LaFleur, and the scheme is expected to cater to Mariota's strengths as opposed to square-pegging him into a round hole like the old staff. We've heard it before, but Mariota has big breakout potential in 2018.",
                          "Broncos GM John Elway said at the Combine his plan is to keep Emmanuel Sanders and Demaryius Thomas. The offseason began with speculation the Broncos might dangle Sanders for trade, but that would be selling low on a dynamic No. 2 wideout when healthy. Sanders ineffectively played through a high ankle sprain last year, and poor quarterback play exacerbated matters. Sanders and Thomas remain the strength of the Broncos' offense. Denver still badly needs to find a No. 3 pass option.",
                          "Browns head coach Hue Jackson confirmed Tyrod Taylor is the team's starting quarterback. Cabot continues that Jackson said he'll resist the temptation to throw Baker Mayfield in 'too soon'. Although Jackson has confirmed Taylor's status as Cleveland's Week 1 starter numerous times throughout the offseason, it's likely Taylor will be given a short leash. The former Bills QB has only one year remaining on his current deal and will likely give way to the No. 1 overall pick sooner rather than later this upcoming season.",
                          "There is no news about this player currently","Packers signed TE Jimmy Graham, formerly of the Seahawks, to a three-year contract. Graham appeared headed for a reunion with the Saints, but the sides couldn't figure out the financials. Graham is coming off his first double-digit touchdown campaign since 2014 but saw his yards per catch crater from 14.2 to 9.1 last season. The drop off came even as Graham was another year removed from his devastating knee injury. Now 31, he required frequent maintenance days in Seattle. Despite his advancing age and seeming loss of a step, Graham is an intriguing pairing with a quarterback who at one point coaxed an eight-score season out of Richard Rodgers.",
                          "Matthew Stafford completed 20-of-29 passes for 323 yards and three touchdowns in the Lions' Week 17 win over the Packers. He also caught -- yes, caught -- a two-point conversion from Golden Tate. Stafford had one of his best seasons to date, completing 371-of-565 passes (65.7%) for 4,446 yards (7.9 YPA) and a 29:10 TD:INT mark. The YPA average set a new career high, while the 10 picks matched a season-best that Stafford set last year. He's cut down on the turnovers in recent years and was playing at an MVP level part of this season before the Lions fell out of the playoff picture. Stafford just signed a massive extension in August and is inked through 2022. With coach Jim Caldwell expected to be fired, it's possible Stafford will have to learn a new offense in 2018, unless the new coach keeps OC Jim Bob Cooter, who has done wonders with Stafford the past two years.",
                          "Will Fuller is undergoing minor knee surgery, and is expected to be full go in 'a few weeks.' However minor Fuller's operation is — it sounds like a scope — it's a fitting end to an injury-marred sophomore campaign. Fuller broke his collarbone in camp before dealing with a ribs issue for most of the regular campaign. He was limited to 10 appearances, and has now missed eight games in two years as an NFLer. The 6-foot-0, 185-pound speedster needs to make increased durability an offseason focus.",
                          "There is no news about this player currently",
                          "Panthers signed Greg Olsen to a two-year, $17.1 million extension through 2020. The deal reportedly can be worth $20.1 million with incentives. Olsen was scheduled to be a free agent after this year and was even linked with some TV jobs, but now he is under contract through his age-35 season. Olsen played just seven games last year because of a foot injury and was never the same after he returned. He says he is completely healed now, however, and should remain one of the top options in Carolina's passing attack.",
                          "Odell Beckham (ankle) participated in individual drills on Thursday. Still recovering from an ankle injury, Beckham is not practicing this week, but participating in individual drills suggests he is close to full health. The Giants will likely take it slow with their star receiver, but it looks like he will be healthy enough to participate in OTAs. ",
                          "Panthers OC Norv Turner said the team will 'keep finding ways' to get Christian McCaffrey the ball. 'He had an unbelievable rookie year and did a lot more than a lot of people would be asked to do and handled them all,' said Turner, who compared McCaffrey favorably to one of his former players, Darren Sproles. 'He's got such talent, you're just going to keep finding ways to get him the ball and try to create more space for him.' McCaffrey was so-so as a ball-carrier in year one (3.7 yards per carry), but excelled in the passing game with 80 catches, which ranked third in the league among running backs. Power back Jonathan Stewart will continue to be involved, though McCaffrey should be in for a bigger workload next season.",
                          "Browns agreed to terms with RB Carlos Hyde, formerly of the 49ers, on a three-year, $15 million contract. This feels like spending money just to spend it. Hyde went to Ohio State and is from the state, so it's a homecoming of sorts for him. However, he isn't all that different from ex-Brown Isaiah Crowell, who left for the Jets on Tuesday and wasn't used often enough by coach Hue Jackson. The Browns also have Duke Johnson and have been linked to Saquon Barkley at the top of the draft. Hyde is now a top-eight-paid running back in the NFL at $5 million annually. It's going to be really hard to get behind him in fantasy after seeing Crowell's usage last season.",
                          "Davante Adams says there are no lingering effects from his two 2017 concussions. Adams sat out Weeks 16 and 17 after being concussed by Thomas Davis in Week 15, but his agent said he could have appeared in 'at least' one of those games. Adams has suffered three concussions since the beginning of the 2016 season, but neither he nor the Packers — who gave Adams a four-year, $58 million extension on Dec. 29 — seem concerned.",
                          "Alshon Jeffery (shoulder) remains in a sling but hopes to be ready for the preseason. He's six weeks removed from surgery to repair a torn rotator cuff in his right shoulder and has already been ruled out for OTAs. Jeffery admits he hasn't done much since the surgery but as of now, there's no concern about his status for Week 1. The South Carolina alum agreed to a four-year extension in December, keeping him in Philadelphia through his age-31 season. ",
                          "The MLB's Texas Rangers traded Russell Wilson to the New York Yankees. Wilson played his college baseball at NC State and was drafted by the Colorado Rockies in the fourth round in 2010. In 2013, he was dealt to the Rangers and went to spring training in 2014 and 2015. He has always dreamed of playing for the Yankees, Wilson says, and plans to attend spring training with the Bronx Bombers this year. Wilson still has no plans to be a dual-sport athlete.",
                          "Bears signed WR Allen Robinson, formerly of the Jaguars, to a three-year, $42 million contract. The deal reportedly includes $25 million in guarantees. With one of the weakest receiver corps in the league, the Bears were always expected to make a splash in free agency, and Robinson, who is still just 24 and expected to be fully healthy for the offseason, is arguably the cream of the crop. Robinson suffered a torn ACL in 2017 but is only two seasons removed from a 'down' year in which he led the Jaguars across the board with a 73-883-6 line. He steps into immediate opportunity with the Bears, who have 225 targets and nearly 2,000 air yards available from last season's production and a quality offensive mind running the show in new coach Matt Nagy. ",
                          "Andy Dalton said he's looking forward to the Bengals' new revamped playbook. Offensive coordinator Bill Lazor reportedly spent the offseason adjusting Cincinnati's playbook. 'The sense I’m getting is there is going to be a lot of change and a lot of learning,' Dalton said. 'I think we’re going to be multiple.' Lazor replaced Ken Zampese after the Bengals were outscored 33-9 through two games last season. It's great for Dalton's fantasy outlook that, with Lazor calling plays, Cincinnati recorded the fifth-highest passing rate (56%) inside the five-yard line. The Bengals' offense will continue to run through A.J. Green no matter the ensuing changes.",
                          "Deshaun Watson promised 'my game's not changing' despite coming off a torn ACL. 'Whatever you [saw] last year is going to be the same, if not better,' Watson said. 'I've dealt with adversity before, had injuries before. I didn't let that slow me down. It just changed my attitude about the game. A lot of people would think that I'd come back hesitant, but I'm going to make sure I come back more forceful and with a stronger and more intense attitude.' Coach Bill O'Brien has retooled the playbook to cater to Watson's strengths. Watson's 9.3% touchdown rate would have easily been the best in the league had he qualified; he tossed 19 touchdowns across seven games (six starts). He should be full-go for training camp.",
                          "David Njoku caught 2-of-2 targets for 38 yards in the Browns' Week 17 loss to the Steelers. His 34-yard catch and run showed Njoku's tackle-breaking prowess and set up Rashard Higgins' second score. One of the NFL’s most-underutilized rookies, Njoku flashed dynamic playmaking ability in the rare instances the Browns played him, and also made major strides as a run blocker down the stretch. Coach Hue Jackson refused to commit to Njoku as a full-time player, however, even as fellow first-round TEs Evan Engram and O.J. Howard were both 70-plus-percent players in their respective offenses. Only 21 years old, Njoku offers long-term Travis Kelcian upside, but it will be up to the coaching staff to get its best players on the field in 2018.",
                          "Leonard Fournette rushed 24 times for 76 yards and a touchdown in the Jaguars' AFC Championship Game loss to the Patriots, adding two catches for 13 yards. After averaging 3.88 yards on 268 regular season carries, Fournette saw that number fall to 3.45 on 70 postseason totes. The No. 4 overall pick came out strong as a rookie, averaging 99 yards and 4.58 yards per carry over his first six games. Those numbers fell to 63 and 3.22, respectively, over his final seven as he wore down amongst a bevy of injuries. Fournette's ankle, a serious issue at LSU, remained a problem his first year in the big leagues. Fournette emerged from piles for home runs far less often than he did in the SEC. Improved durability will be a must for his sophomore campaign.",
                          "Chiefs signed Sammy Watkins, formerly of the Rams, to a three-year, $48 million contract. The deal reportedly includes $30 million guaranteed, a massive number for a player with a concerning health history. With strong-armed Patrick Mahomes now under center, GM Brett Veach made noise about adding another speedy receiver to play opposite Tyreek Hill, but it is still surprising to see the Chiefs making this big of a splash. Watkins seems to perfectly fit what they were looking for, however. He has averaged over 15 yards per catch in each of his first four seasons, and 13 of his 25 career touchdowns have come from 20 yards or more, although he also showed his ability in the red zone last season. While Watkins would seem to be a good real-life fit, it is fair to wonder how much fantasy value he will return in an offense helmed by a first-year starter with Hill and Travis Kelce demanding targets and Kareem Hunt in the backfield.","Cam Newton was uninjured in a car accident Thursday in Atlanta.Newton's Ferrari F12 was rear-ended by a dump truck at around 4 PM ET. Neither party chose to file a police report. Newton suffered broken bones in his back after flipping his car in 2014, causing him to miss a game against Tampa Bay in Week 15. Luckily this accident wasn't as serious.",
                          "Julio Jones caught 9-of-16 targets for 101 yards in the Falcons' Divisional Round loss to the Eagles. Jones went 9/90 in each of the Falcons' playoff games. Although Jones' 88/1,444/3 regular season carried an air of disappointment in fantasy football — three touchdowns, really? — Jones' 1,444 yards were second in the league, as well as the third most of his career. He's cleared 1,400 yards 4-of-4 years since his serious 2013 foot injury. One month shy of his 29th birthday, Jones has yet to display any physical drop-off. One of these years, he's going to regress to the touchdown mean and put up at least 10. He will remain a top-five fantasy wideout for 2018.",
                          "Rams exercised RB Todd Gurley's fifth-year team option for 2019. After contending for the league's MVP award last season, Gurley is now set to make roughly $9.63 million in what will be the final year of his rookie contract in 2019. A prodigious talent freed from Jeff Fisher's anti-offense, 24-year-old (in August) Gurley should have another monster campaign in 2018.",
                          "CSN Mid-Atlantic's JP Finlay reports Jamison Crowder is open to a contract extension with the Redskins. Crowder has one year left on his rookie deal at around the league minimum, so of course he'd be open to a new deal. He reportedly likes it playing in D.C. for coach Jay Gruden. Crowder had his best season in 2016 and took a step back this past year while playing through multiple injuries. Crowder really got off to a horrid start but was able to turn it on the second half of the year when Jordan Reed was out and Terrelle Pryor had been phased out of the offense.",
                          "Eli Manning said he and the Giants have not discussed his place in the organization beyond 2018. Manning is under contract through 2019, but the Giants could save $17 million against the cap by releasing him next spring. That makes this season something of a make-or-break situation, especially if New York drafts a quarterback early. 'This league, it's one year at a time,' Manning said. 'I need to go out there and play well this year, and that's all I'm looking forward to.' Manning averaged 6.1 yards per attempt last season while leading the second-worst offense in the league.",
                          "Evan Engram (rib) is inactive for Week 17 against the Redskins. Engram hoped to play in the season finale, so this injury does not appear to be one which will affect his offseason. The No. 23 overall pick in this year's draft, Engram was one of the rarest of all NFL entities, a rookie producer at tight end. Despite sitting out one game and playing in perhaps the worst offense in the league, Engram finishes his rookie campaign with 64 catches for 722 yards and six scores. Targets are unlikely to be as plentiful with Odell Beckham back healthy next season, but Engram will be solidly inside the top-ten at the position next summer.",
                          "Chargers placed TE Hunter Henry (kidney) on injured reserve, ending his season. OG Brett Boyko was signed off the practice squad in the corresponding move. Henry suffered a small kidney laceration in Saturday's loss to Kansas City. Henry took a step forward in his sophomore season, securing 45-of-63 targets for 579 yards and four touchdowns over 14 appearances. Without him, the Chargers will turn to veteran Antonio Gates at tight end.",
                          "ESPN Saints reporter Mike Triplett reports 'at least one other team' was willing to give Drew Brees $60 million guaranteed over two years in free agency. Brees re-upped with the Saints for two years, $50 million, just $27 million of which is guaranteed. Brees took a discount to remain with the franchise he's been with since 2006. Money aside, even if the $60 million team was the loaded Vikings, Brees probably made the right decision remaining in the setup that's made him a future Hall-of-Famer.",
                          "Devonta Freeman (knee) could be ready for the start of OTAs. Freeman avoided surgery after playing through MCL and PCL sprains last season. His timetable puts him on track for OTAs, but the Falcons may move him slowly. Even if Freeman is limited this offseason, he'll be fully healthy for training camp.",
                          "Stefon Diggs caught 8-of-12 targets for 70 yards in the Vikings' NFC title game loss to the Eagles. Diggs took a knee to the back on his first catch and didn’t seem right the rest of the way, appearing stiff on his routes and checking out of the game a few times. It was an anticlimactic ending to Diggs’ season after his heroic 61-yard game-winning touchdown in the Divisional Round. Diggs capped his third NFL campaign with a 64/849/13.3/8 receiving line, continuing to show game-breaking ability even as Adam Thielen emerged as the Vikings’ higher-volume wideout. Still only 24 years old, Diggs will again be an early- to middle-round fantasy pick in 2018, which is Diggs’ contract year.",
                          "T.Y. Hilton reported to the Colts' offseason program in 'the best shape of his life.' Hilton reported to Indy's workout program thinner after he completely cut out fast food from his diet during the offseason. He worked closely with Indy's new director of sports performance, Rusty Jones, to alter his nutrition plan. Hilton wasn't drafted or extended by GM Chris Ballard, but it's telling how much the front office believes he'll bounce back in that he survived the regime's overhaul after the season. The speed demon desperately needs Andrew Luck to return healthy for 2018.",
                          "The Broncos have exercised Demaryius Thomas' $4 million option bonus. It locks Thomas into $12.5 million between salary and bonuses in 2018. Now on the wrong side of 30, Thomas is coming off his first sub-1,000 yard season since 2011 (Tebow Time). The Broncos seem to be assuming the down year was quarterback related, which is a safe assumption. Case Keenum is hardly a star, but he's a major upgrade on what the Broncos had in 2017, and improves Thomas' fantasy prospects.",
                          "Bucs exercised Jameis Winston's fifth-year option for 2019.There was never any doubt Tampa would pick up the option. Winston is now scheduled to earn an injury-guaranteed $20.922 million in 2019, but it is likely the Bucs explore an extension before Winston enters the final year of his deal. The No. 1 overall pick of the 2015 draft, Winston has thrown 69 touchdowns against 44 interceptions through his first three years in the league.",
                          "Bengals re-signed TE Tyler Eifert to a one-year contract. The deal carries a maximum value of $8 million, according to NFL Network's Tom Pelissero. Eifert has barely played the last two years while battling chronic back issues, but led all tight ends with 13 touchdowns in 2015. The 27-year-old has been a dangerous red-zone presence throughout his career but has to prove he can stay healthy. ",
                          "Raiders acquired WR Martavis Bryant from the Steelers in exchange for the No. 79 overall pick. The Steelers let it be known they were ready to trade their walk-year wideout, and the Raiders stepped in immediately. 26-year-old Bryant is headed to a receiver corps that already includes Amari Cooper and Jordy Nelson, but will have bounce-back potential after a slow start and coach clashing marred his 2017 return from indefinite suspension. It's no sure thing Bryant meshes with back to the future coach Jon Gruden, but he still offers legitimate upside. Bryant is a gargantuan touchdown scorer who is a threat to rip a big play every time he touches the ball. All that being said, it's a steep price for a free agent to be with a lengthy suspension history.",
                          "Coach Steve Wilks said he 'would still say' Sam Bradford is the Cardinals' starting quarterback if the season started today. 'I’m very excited about Josh [Rosen], what he can bring,' Wilks continued. 'Every position is open for competition.' Bradford is guaranteed $15 million this season, so we'd envision him getting every opportunity to open the season as the starter. However, the Cardinals are in a bit of a mini-rebuild and don't stand much to gain by starting Bradford, especially if No. 10 overall pick Rosen proves ready for the big show. The elephant in the room is also Bradford's extensive injury history. We'd bet on Rosen making rookie-year starts in the desert.",
                          "Randall Cobb caught 4-of-6 targets for 45 yards and one touchdown in the Packers' Week 17 loss to the Lions. He also completed a 10-yard pass to Brett Hundley and rushed once for four yards. Since signing his big deal in 2015, Cobb has taken a back seat in the offense with the emergence of new No. 1 wideout Davante Adams. Cobb's 66 catches for 658 yards and four touchdowns this season were all four-year lows, and his 10.0 YPR also marked a new career low. Cobb is still just 27 but is entering the final year of his contract that is set to pay him an $8.6 million salary. Strapped with a $12.75 million cap number in 2018, the Packers can clear $9.5 million of it by releasing Cobb. It seems like a probable move after Green Bay just paid Adams. Cobb shouldn't struggle to find work if it happens, and he could even use a change of scenery at this point."]
    
    
    var playerArray: [players] = []
    var filteredData = [String]()
    var inSearchMode = false
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView.delegate = self
        tableView.dataSource = self
        
        searchBar.delegate = self
        searchBar.returnKeyType = UIReturnKeyType.done
        
        for index in 0...name.count - 1 {
            playerArray.append(players(name: name[index], position: position[index], salary: salary[index], yearsLeft: yearsLeft[index], owner: owner[index], rotoworldBlurb: rotoworldBlurb[index]))
        }
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "ShowPlayer" {
            let destination = segue.destination as! PlayerDetailViewController
            var selectedIndexPath = tableView.indexPathForSelectedRow!
            if inSearchMode {
                destination.player = getPlayer(name: filteredData[selectedIndexPath.row])
            } else {
                destination.player = playerArray[selectedIndexPath.row]
            }
        } else {
            if let selectedPath = tableView.indexPathForSelectedRow {
                tableView.deselectRow(at: selectedPath, animated: true)
            }
        }
    }
    
    @IBAction func unwindFromStudentDetail(segue: UIStoryboardSegue) {
        let source = segue.source as! PlayerDetailViewController
        if let selectedIndexPath = tableView.indexPathForSelectedRow {
            playerArray[selectedIndexPath.row] = source.player
            tableView.reloadRows(at: [selectedIndexPath], with: .automatic)
        } else {
            let newIndexPath = IndexPath(row: name.count, section: 0)
            playerArray.append(source.player)
            tableView.insertRows(at: [newIndexPath], with: .bottom)
            tableView.scrollToRow(at: newIndexPath, at: .bottom, animated: true)
        }
    }
    
    func getPlayer(name: String) -> players {
        for player in playerArray {
            if player.name == name {
                return player
            }
        }
        return playerArray[0]
    }
    
    // MARK: - UITableViewDataSource
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if inSearchMode {
            return filteredData.count
        }
        return name.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = tableView.dequeueReusableCell(withIdentifier: "Cell", for: indexPath) as? DataCell {
            let text: String!
            
            if inSearchMode {
                text = filteredData[indexPath.row]
            } else {
                text = name[indexPath.row]
            }
            cell.layer.borderWidth = 2.0
            cell.layer.borderColor = UIColor.white.cgColor
            cell.congigureCell(text: text)
            return cell
        } else {
            return UITableViewCell()
        }
    }
    
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        if searchBar.text == nil || searchBar.text == "" {
            inSearchMode = false
            view.endEditing(true)
            tableView.reloadData()
        } else {
            inSearchMode = true
            filteredData = name.filter({$0.contains(searchBar.text!)})
            tableView.reloadData()
        }
    }
}

